{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mlflow.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
#    kubernetes.io/ingress.class: "gce-internal"
spec:
  backend:
    serviceName: {{ default $fullName .serviceNameOverride }}
    servicePort: {{ default $svcPort .servicePortOverride }}
{{- end }}
