apiVersion: skaffold/v2beta4
build:
  artifacts:
  - context: .
    docker:
      dockerfile: Dockerfile
    image: gcr.io/asl-ml-immersion/tfx_covertype_continuous_training
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
kind: Config
